### ISSUE TITLE
Star rating still allows 0 rating

### ISSUE THREAD

**Issue by Joskef** [VincentII/Praxis-Survey#1]
![image](https://cloud.githubusercontent.com/assets/17984538/22727048/abe2c0c8-ee11-11e6-93a2-a334e4215803.png)

The "-" allows the user to remove their answers from the rating.

Consider placing the likert scale ("Neutral, Good, Very Good etc.) under the stars for less clamped space.

**Comment by VincentII** [comment]
Fixed, Please Check

**Comment by Joskef** [comment]
Problem has bee fixed.
