### ISSUE TITLE
Disable user zooming capabilities

### ISSUE THREAD

**Issue by Joskef** [VincentII/Praxis-Survey#7]
![image](https://cloud.githubusercontent.com/assets/17984538/22911736/305fc024-f29c-11e6-8430-63d21c698e00.png)

Currently the user is allowed to zoom in the web app allowing objects to get cut off from the screen.

A number of solutions are available here:

http://stackoverflow.com/questions/4472891/how-can-i-disable-zoom-on-a-mobile-web-page

**Comment by VincentII** [comment]
Wont Fix
