### ISSUE TITLE
Comment Box

### ISSUE THREAD

**Issue by Joskef** [VincentII/Praxis-Survey#8]
![image](https://cloud.githubusercontent.com/assets/17984538/22916167/cc7ef1f8-f2b7-11e6-9bab-7e45414d1c9d.png)

Currently the editable text box has the instructions of what the purpose of the object is.

It would be nice if its separated into a label so the instruction or hint does not disappear once the user starts typing their answers.

The user is also allowed to type in 1 character (a space for example) and it is not considered a blank message. This kinds of messages get saved in the database without it being actually useful.

**Comment by VincentII** [comment]
Fixed
